package native

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/graphql-go/graphql"
	"github.com/graphql-go/graphql/language/ast"
)

// GraphQLHandler serves the MockRTC-compatible admin session API consumed by
// the bundled webextension's MockRTCRemotePeer/RemoteSessionApi client (see
// assets/overrides/webextension/build/background.js). This is a from-scratch
// Go implementation of the wire protocol actually observed in that bundle —
// it deliberately reuses the same github.com/graphql-go/graphql engine
// already used for the REST /graphql endpoint (internal/api/gql), rather
// than adding a second GraphQL dependency.
func GraphQLHandler(h *Handler) http.Handler {
	schema := buildRTCSchema(h)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "only POST requests are supported", http.StatusMethodNotAllowed)
			return
		}
		var req struct {
			Query         string         `json:"query"`
			Variables     map[string]any `json:"variables"`
			OperationName string         `json:"operationName"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "invalid JSON body", http.StatusBadRequest)
			return
		}
		result := graphql.Do(graphql.Params{
			Schema:         schema,
			RequestString:  req.Query,
			VariableValues: req.Variables,
			OperationName:  req.OperationName,
			Context:        context.Background(),
		})
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
}

var jsonScalar = graphql.NewScalar(graphql.ScalarConfig{
	Name:         "Raw",
	Description:  "An arbitrary JSON value",
	Serialize:    func(value any) any { return value },
	ParseValue:   func(value any) any { return value },
	ParseLiteral: func(valueAST ast.Value) any { return nil },
})

var sessionDescriptionType = graphql.NewObject(graphql.ObjectConfig{
	Name: "SessionDescription",
	Fields: graphql.Fields{
		"type": {Type: graphql.NewNonNull(graphql.String)},
		"sdp":  {Type: graphql.NewNonNull(graphql.String)},
	},
})

var sessionDescriptionInput = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "SessionDescriptionInput",
	Fields: graphql.InputObjectConfigFieldMap{
		"type": {Type: graphql.NewNonNull(graphql.String)},
		"sdp":  {Type: graphql.NewNonNull(graphql.String)},
	},
})

// offerResultType covers both the peer-level result shape ({id, description})
// and the session-scoped shape ({description}) — GraphQL only resolves the
// fields the caller's query text actually selects, so one type can serve
// both call sites in background.js (MockRTCRemotePeer vs RemoteSessionApi).
var offerResultType = graphql.NewObject(graphql.ObjectConfig{
	Name: "OfferResult",
	Fields: graphql.Fields{
		"id":          {Type: graphql.String},
		"description": {Type: graphql.NewNonNull(sessionDescriptionType)},
	},
})

type offerResult struct {
	id          string
	description SessionDescription
}

func parseSessionDescription(v any) SessionDescription {
	m, _ := v.(map[string]any)
	sdp, _ := m["sdp"].(string)
	typ, _ := m["type"].(string)
	if typ == "" {
		typ = "offer"
	}
	return SessionDescription{Type: typ, SDP: sdp}
}

func buildRTCSchema(h *Handler) graphql.Schema {
	mutationType := graphql.NewObject(graphql.ObjectConfig{
		Name: "Mutation",
		Fields: graphql.Fields{
			// createOffer(peerId, sessionId?, options) — top-level
			// (MockRTCRemotePeer) when sessionId is absent, session-scoped
			// (RemoteSessionApi) when present. Both return an offer SDP
			// generated by a real pion PeerConnection.
			"createOffer": {
				Type: graphql.NewNonNull(offerResultType),
				Args: graphql.FieldConfigArgument{
					"peerId":    {Type: graphql.NewNonNull(graphql.ID)},
					"sessionId": {Type: graphql.ID},
					"options":   {Type: jsonScalar},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					peerID, _ := p.Args["peerId"].(string)
					sessionID, offer, err := h.CreateOffer(peerID)
					if err != nil {
						return nil, err
					}
					return offerResult{id: sessionID, description: offer}, nil
				},
			},
			"createExternalOffer": {
				Type: graphql.NewNonNull(offerResultType),
				Args: graphql.FieldConfigArgument{
					"peerId":  {Type: graphql.NewNonNull(graphql.ID)},
					"options": {Type: jsonScalar},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					peerID, _ := p.Args["peerId"].(string)
					sessionID, offer, err := h.CreateOffer(peerID)
					if err != nil {
						return nil, err
					}
					return offerResult{id: sessionID, description: offer}, nil
				},
			},
			// answerOffer(peerId, sessionId?, offer, options) — the browser
			// is initiating; we answer with a real pion PeerConnection.
			"answerOffer": {
				Type: graphql.NewNonNull(offerResultType),
				Args: graphql.FieldConfigArgument{
					"peerId":    {Type: graphql.NewNonNull(graphql.ID)},
					"sessionId": {Type: graphql.ID},
					"offer":     {Type: graphql.NewNonNull(sessionDescriptionInput)},
					"options":   {Type: jsonScalar},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					peerID, _ := p.Args["peerId"].(string)
					offer := parseSessionDescription(p.Args["offer"])
					sessionID, answer, err := h.AnswerOffer(peerID, offer)
					if err != nil {
						return nil, err
					}
					return offerResult{id: sessionID, description: answer}, nil
				},
			},
			"answerExternalOffer": {
				Type: graphql.NewNonNull(offerResultType),
				Args: graphql.FieldConfigArgument{
					"peerId":  {Type: graphql.NewNonNull(graphql.ID)},
					"offer":   {Type: graphql.NewNonNull(sessionDescriptionInput)},
					"options": {Type: jsonScalar},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					peerID, _ := p.Args["peerId"].(string)
					offer := parseSessionDescription(p.Args["offer"])
					sessionID, answer, err := h.AnswerOffer(peerID, offer)
					if err != nil {
						return nil, err
					}
					return offerResult{id: sessionID, description: answer}, nil
				},
			},
			// completeOffer(peerId, sessionId, answer) — the browser has
			// answered an offer the mock peer generated via createOffer.
			"completeOffer": {
				Type: graphql.NewNonNull(graphql.Boolean),
				Args: graphql.FieldConfigArgument{
					"peerId":    {Type: graphql.NewNonNull(graphql.ID)},
					"sessionId": {Type: graphql.NewNonNull(graphql.ID)},
					"answer":    {Type: graphql.NewNonNull(sessionDescriptionInput)},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					sessionID, _ := p.Args["sessionId"].(string)
					answer := parseSessionDescription(p.Args["answer"])
					if err := h.CompleteOffer(sessionID, answer); err != nil {
						return false, err
					}
					return true, nil
				},
			},
		},
	})

	queryType := graphql.NewObject(graphql.ObjectConfig{
		Name: "Query",
		Fields: graphql.Fields{
			"getSeenMessages": {
				Type: graphql.NewNonNull(graphql.NewList(jsonScalar)),
				Args: graphql.FieldConfigArgument{
					"peerId":      {Type: graphql.NewNonNull(graphql.ID)},
					"channelName": {Type: graphql.String},
				},
				Resolve: func(p graphql.ResolveParams) (any, error) {
					peerID, _ := p.Args["peerId"].(string)
					channelName, _ := p.Args["channelName"].(string)
					return h.GetSeenMessages(peerID, channelName), nil
				},
			},
		},
	})

	// offerResultType's fields need a resolver that reads from our internal
	// offerResult struct — graphql-go defaults to reflection-based field
	// access by exported name, so we attach explicit resolvers instead since
	// our struct fields are unexported.
	offerResultType.AddFieldConfig("id", &graphql.Field{
		Type: graphql.String,
		Resolve: func(p graphql.ResolveParams) (any, error) {
			if r, ok := p.Source.(offerResult); ok {
				return r.id, nil
			}
			return nil, nil
		},
	})
	offerResultType.AddFieldConfig("description", &graphql.Field{
		Type: graphql.NewNonNull(sessionDescriptionType),
		Resolve: func(p graphql.ResolveParams) (any, error) {
			if r, ok := p.Source.(offerResult); ok {
				return map[string]any{"type": r.description.Type, "sdp": r.description.SDP}, nil
			}
			return nil, nil
		},
	})

	schema, _ := graphql.NewSchema(graphql.SchemaConfig{
		Query:    queryType,
		Mutation: mutationType,
	})
	return schema
}
