// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrontendLog(arg1, arg2) {
  return window['go']['main']['ShellApp']['FrontendLog'](arg1, arg2);
}

export function GetDesktopVersion() {
  return window['go']['main']['ShellApp']['GetDesktopVersion']();
}

export function GetLogPath() {
  return window['go']['main']['ShellApp']['GetLogPath']();
}

export function GetMockttpPort() {
  return window['go']['main']['ShellApp']['GetMockttpPort']();
}

export function GetServerAuthToken() {
  return window['go']['main']['ShellApp']['GetServerAuthToken']();
}

export function GetServerPort() {
  return window['go']['main']['ShellApp']['GetServerPort']();
}

export function IsHarAssociated() {
  return window['go']['main']['ShellApp']['IsHarAssociated']();
}

export function OpenExternalAuth(arg1) {
  return window['go']['main']['ShellApp']['OpenExternalAuth'](arg1);
}

export function OpenHarWithDefaultApp(arg1) {
  return window['go']['main']['ShellApp']['OpenHarWithDefaultApp'](arg1);
}

export function OpenLogFile() {
  return window['go']['main']['ShellApp']['OpenLogFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['ShellApp']['OpenURL'](arg1);
}

export function RegisterHarAssociation() {
  return window['go']['main']['ShellApp']['RegisterHarAssociation']();
}

export function SelectApplication() {
  return window['go']['main']['ShellApp']['SelectApplication']();
}

export function SelectFilePath() {
  return window['go']['main']['ShellApp']['SelectFilePath']();
}

export function SetContext(arg1) {
  return window['go']['main']['ShellApp']['SetContext'](arg1);
}

export function ShutdownServer() {
  return window['go']['main']['ShellApp']['ShutdownServer']();
}

export function UnregisterHarAssociation() {
  return window['go']['main']['ShellApp']['UnregisterHarAssociation']();
}
