// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function FrontendLog(arg1:string,arg2:string):Promise<void>;

export function GetDesktopVersion():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetMockttpPort():Promise<number>;

export function GetServerAuthToken():Promise<string>;

export function GetServerPort():Promise<number>;

export function IsHarAssociated():Promise<boolean>;

export function OpenExternalAuth(arg1:string):Promise<void>;

export function OpenHarWithDefaultApp(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RegisterHarAssociation():Promise<boolean>;

export function SelectApplication():Promise<string>;

export function SelectFilePath():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ShutdownServer():Promise<void>;

export function UnregisterHarAssociation():Promise<boolean>;
